### ISSUE TITLE
Spanish contextual spell check

### ISSUE THREAD

**Issue by JoseZamora97** [R1j1t/contextualSpellCheck#13]
Hi, I loaded this wonderful module into a spacy Spanish model. And did not work. I assume it because the training was done with English dataset. Is three any way to make this algorithm works with Spanish spacy model. Thank you.

**Comment by R1j1t** [comment]
This is good idea. I can make some changes where you can specify your model (some constrains will be there). Let me see what I can do over the weekend. If you like to contribute please feel free to create a PR.

**Comment by JoseZamora97** [comment]
Have you been able to do implement anything?

**Comment by R1j1t** [comment]
@JoseZamora97 the task sounds good for the package but havent had much time to look into it because of some other work.
