### ISSUE TITLE
How to specify bert model?

### ISSUE THREAD

**Issue by wushixian** [R1j1t/contextualSpellCheck#15]
I use spacy 2.3.1 which support chinese model, and I wanna use contextualspellcheck to check chinese spell,but the result is hard to understand, so I think I should specify a chinese bert model.
Can I specify it by code? or I must modify source code to do that?
thanks very much.

**Comment by R1j1t** [comment]
At present, you will have to modify the source code. I have this use case in mind and because we use transformers package it should be relatively easy. If you think you can contribute, please raise a PR for it! I would be happy to see new contributions.

**Comment by wushixian** [comment]
OK，I really wanna try it. Thanks very much.

**Comment by wushixian** [comment]
I tried ro modify the code, and used bert-base-chinese model, but the result was not ideal, I'll try to fine-tuning the model.

**Comment by R1j1t** [comment]
@wushixian did you consider the edit distance logic? I dont think it will be same as english. Maybe you need to modify [this](https://github.com/R1j1t/contextualSpellCheck/blob/master/contextualSpellCheck/contextualSpellCheck.py#L293) function.

**Comment by wushixian** [comment]
Thanks for the remind, I'll try to modify the function.
