### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by sshobham** [R1j1t/contextualSpellCheck#16]
'charmap' codec can't decode byte 0x90 in position 3920: character maps to undefined 
while adding contextualSpellCheck to spacy pipeline

**Comment by R1j1t** [comment]
@sshobham this error is fixed and the latest code is in the master. This issue is similar to #11 and @gaurav0804 suggested the fix as well. I will release the latest code to pypi and you would be able to download it from pip.

**Comment by sshobham** [comment]
Thanks for the update
