### ISSUE TITLE
Improve general code quality for maintenance purposes 

### ISSUE THREAD

**Issue by AlvaroCavalcante** [R1j1t/contextualSpellCheck#25]
**Is your feature request related to a problem? Please describe.**
In my last contribution, I noticed that the code has some improvements that can be done to let it be easier to maintain. The linting note reveals that has some work to do! 
![image](https://user-images.githubusercontent.com/37350513/94607426-4578bd00-0272-11eb-8003-72cea8914193.png)

**Describe the solution you'd like**
I would like to create a PR to improve the code style. The changes will not affect the functioning of the lib.

**Comment by R1j1t** [comment]
@AlvaroCavalcante that is a low score, could you please help me provide the details, where I can run the test? Flake8 was added (https://github.com/R1j1t/contextualSpellCheck/pull/23) and I believe that would have improved the code style (but 2.86?). If you want you can open a PR and suggest improvements!

**Comment by AlvaroCavalcante** [comment]
@R1j1t This score is from contextualSpellCheck.py I ran this command: 
```pylint --reports=y .```  inside "contextualSpellCheck" folder. I'll create a PR to solve some of the reported issues to try to increase the score ok?

**Comment by R1j1t** [comment]
I will have a look at pylint. Thanks for informing me about this, I had no idea. I will also have a look at how the metric is calculated and the suggestions `pylint` makes.

Please create a PR and I will merge it.  Thanks for the info and contribution!

**Comment by AlvaroCavalcante** [comment]
@R1j1t I was looking for an older version of branch master, after sync, I checked that the lint quality is good, sorry! I'll close this issue.

**Comment by R1j1t** [comment]
I also ran the test locally and got the score of 7.93/10 for contextualSpellCheck.py. Some of the suggestions were good. I will not add it to github actions for now but will be a nice addition for sure.
