### ISSUE TITLE
[BUG] Apostrophes

### ISSUE THREAD

**Issue by nicno90** [R1j1t/contextualSpellCheck#26]
**Removing "s" after apostrophe**
When apostrophes are in sentence yields weird results.

**To Reproduce**
```py
#Steps to reproduce the behavior:
1. Init spacy model '...'
2. Add contextualSpellCheck '....'
3. supply the sentence "Spell Checking based on Peter Norvig’s blog post."
4. doc._.outcome_spellCheck gives result: "Spell Checking based on Peter Norvig, blog post."
```

**Expected behavior**
" 's " should not be touched. 

**Version (please complete the following information):**
 - contextualSpellCheck [e.g. 0.3.0]
 - Spacy: [e.g. 2.3.2]
 - transformers [e.g. 3.1.0]

**Comment by R1j1t** [comment]
I tried running the given sentence and it worked as expected on my local. If there is no spelling correction then it returns `''` as mentioned in the [README](https://github.com/R1j1t/contextualSpellCheck#spacydoc-level-extensions).

```py
>>> import spacy
>>> import contextualSpellCheck
>>> nlp = spacy.load("en") 
>>> contextualSpellCheck.add_to_pipe(nlp)
<spacy.lang.en.English object at 0x7f911cef4a90>
>>> nlp.pipe_names
['tagger', 'parser', 'ner', 'contextual spellchecker']
>>> doc = nlp('Spell Checking based on Peter Norvig’s blog post.')
>>> doc._.outcome_spellCheck
''
>>> 
```

Please provide the code to replicate and version info of the package if you are not using the latest.

**Comment by nicno90** [comment]
`nlp = spacy.load('en_core_web_lg')
spell_checker = ContextualSpellCheck(max_edit_dist=4)
nlp.add_pipe(spell_checker)


def correct_spelling(sentence):
    global nlp
    doc = nlp(sentence)
    return doc._.outcome_spellCheck


print(correct_spelling2("Pure Python Spell Checking based on Peter Norvig’s blog post on setting up a simple spell checking algorithm."))
`

**Version (please complete the following information):**
 - contextualSpellCheck == 0.3.0
 - Spacy == 2.3.2
 - transformers == 3.3.1

**Comment by R1j1t** [comment]
Thanks @nicno90 I will have a look.

**Comment by R1j1t** [comment]
I checked and have found the issue.

When using `en_core_web_sm`, token `'s` is identified as `PERSON` from spaCy pipeline but in `en_core_web_lg` it is not identified as `PERSON`. Below is my logic to identify misspell.

https://github.com/R1j1t/contextualSpellCheck/blob/96cb79e968c3d6d1caffff4e5f1fbc8476dad3b0/contextualSpellCheck/contextualSpellCheck.py#L242-L254

`token.ent_type_ != "PERSON"` is causing the issue. I will try to fix it and release it by next weekend. 

Thank you for identifying this issue!

**Comment by nicno90** [comment]
@R1j1t  Thank you for looking into it!

**Comment by R1j1t** [comment]
@nicno90 I have added the fix and test cases. I will release it to PyPi in the next couple of hours.
