### ISSUE TITLE
Training model on my Own dataset (Transfer Learning)

### ISSUE THREAD

**Issue by murtuzamdahod** [R1j1t/contextualSpellCheck#29]
Hello @R1j1t ,
Greetings for the day,

I have a dataset of 20 lakh food item names and I want to build a spell correct model using my own dataset. Can you please guide me on how can I do that?

**Comment by R1j1t** [comment]
@murtuzamdahod I dont have much information to comment but please check this related issue #24 if it can help!

**Comment by R1j1t** [comment]
I will close this PR. Please feel free to open another one if you have any questions
