### ISSUE TITLE
How to replace the text in spacy pipeline with spell_checked text.

### ISSUE THREAD

**Issue by abal6725** [R1j1t/contextualSpellCheck#31]
Hello,

Perhaps this is not a question for you, but I am trying to use the spell checker in my pipeline and I am trying use the spell_checked text for further use in my pipeline. I am running into issues while doing this. Do you have any advice? Thanks!

**Comment by R1j1t** [comment]
@abal6725 it is difficult to infer what you are trying to achieve but have a look at [token level extension](https://github.com/R1j1t/contextualSpellCheck#spacytoken-level-extensions) which gives the information of suggestion and confidence score. There are document and span level extensions as well if that would work as well.
