### ISSUE TITLE
dependency version number in setup.py

### ISSUE THREAD

**Issue by R1j1t** [R1j1t/contextualSpellCheck#38]
This will help prevent code break when some user has an old dependency.

Considerations: Will need to check the lowest version to minimise the unnecessary updates

**Comment by AlvinKuruvilla** [comment]
Hi I would like to take up this issue, how exactly would we go about checking minimum versions

**Comment by R1j1t** [comment]
Thanks @AlvinKuruvilla for your contribution! There is no restriction to have the lowest version possible as dependency. You can check if all the tests pass for the last major release (1.x or 2.x etc) for the core dependency.

https://github.com/R1j1t/contextualSpellCheck/blob/f8cbeb8a7d5dc085f9f8cc5d27d390848d2df274/setup.py#L31

If the tests fail then maybe will have to check the required minor version based on the test result.

**Comment by R1j1t** [comment]
Changes incorporated here: https://github.com/R1j1t/contextualSpellCheck/pull/52/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L31
