### ISSUE TITLE
Can we replace incorrect spelled word with correct spelled?

### ISSUE THREAD

**Issue by ajinkya2903** [R1j1t/contextualSpellCheck#46]
I want to replace the wrong spelled word with the correct spelled word instead of replacing it with the contextual word. Is this possible?

**Comment by R1j1t** [comment]
Can you have a look at the [examples](https://github.com/R1j1t/contextualSpellCheck/blob/master/examples/en_example.py) folder? I think `doc._.outcome_spellCheck` is needed. Please read the [doc](https://github.com/R1j1t/contextualSpellCheck#extensions) if you need any clarification.
