### ISSUE TITLE
Unnecessary dependency on flask

### ISSUE THREAD

**Issue by kshitij12345** [R1j1t/contextualSpellCheck#47]
From what I see, `flask` is only used in the example file `modelAPI.py` in `RESTAPI`.

The core code is not at all dependent on `flask`, however it is a required dependency
https://github.com/R1j1t/contextualSpellCheck/blob/f8cbeb8a7d5dc085f9f8cc5d27d390848d2df274/requirements.txt#L1

I think it would be better to just add note in `modelAPI.py` to install flask and remove it from `requirements.txt`.

Thanks for the interesting project.

**Comment by R1j1t** [comment]
That is a valid point. My reasoning for not removing `Flask` was, this repository has a dependency on it. Core functionality dependency is better captured in `setup.py` below:

https://github.com/R1j1t/contextualSpellCheck/blob/f8cbeb8a7d5dc085f9f8cc5d27d390848d2df274/setup.py#L31

I would not mind having a `requirement.txt` in _RESTAPI_ folder. But I was not sure so I just left it. I will check on the best practice and then maybe change it.

And, I am happy you liked the project! Please feel free to contribute!

**Comment by R1j1t** [comment]
I tried to find any relevant PEP to identify what is the recommended way of using `requirement.txt` but was not able to find anything specific.

[PEP 518](https://www.python.org/dev/peps/pep-0518/#abstract) talks about minimum build requirement in setup.py (which this follows). I think the discussion is valid and I will be happy to create `requirement.txt` in `examples`. I decision is biased based a similar experience I had when one of the optional dependencies choked the CI and I had to comment that package. @kshitij12345 do you want to pickup this change?

Other similar PEP but not much relevant:
[PEP 508](https://www.python.org/dev/peps/pep-0508/)
[PEP 650](https://www.python.org/dev/peps/pep-0650/)
