### ISSUE TITLE
[BUG] compatibility issue with spacy v3

### ISSUE THREAD

**Issue by virdiprateek** [R1j1t/contextualSpellCheck#48]
I'm testing the way it's mentioned in the examples as follows:

```py
import spacy
from contextualSpellCheck import ContextualSpellCheck

nlp = spacy.load("en_core_web_sm")
checker = ContextualSpellCheck(max_edit_dist=100)
nlp.add_pipe(checker)

doc = nlp("Income was $9.4 milion compared to the prior year of $2.7 milion.")
print(doc._.outcome_spellCheck)
```

Getting error:
```bash
`nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <contextualSpellCheck.contextualSpellCheck.ContextualSpellCheck object at 0x7f923add6c10> (name: 'None')
```

Can you please suggest the fix for this??

**Comment by jonmun** [comment]
This is due to changes introduced in spacy v3: https://nightly.spacy.io/usage/v3#migrating-add-pipe

I've submitted a pull request to fix this issues.

**Comment by R1j1t** [comment]
@virdiprateek as mentioned by @jonmun there might be some issues when using the package with spacy v3. As a temporary solution you can downgrade the spacy to v2.x (if possible for your use case). In the mean time I will check and merge #49 to fix the issue.

Thanks you @jonmun for the PR!!

**Comment by R1j1t** [comment]
@virdiprateek I have updated [contextualSpellCheck 0.3.4 ](https://pypi.org/project/contextualSpellCheck/)

Please try to install the latest package and you will not face this issue. In the mean time I will work on spacy v3 compatibility which I hope to release in a couple of days.
