### ISSUE TITLE
Pipeline dependencies?

### ISSUE THREAD

**Issue by KennethEnevoldsen** [R1j1t/contextualSpellCheck#61]
Wonderful project, seems a lot like something I would like to use for [dacy](https://github.com/KennethEnevoldsen/DaCy), a danish NLP pipeline build on spacy. Currently, it seems like the spelling correction is dependent on the NER and other pipelines? If so this will sadly make it less useful for application before applying the pipeline.

**Comment by R1j1t** [comment]
Hi @KennethEnevoldsen It is great to hear you liked the project! NER and sentence tokenizer is an important to identify if the spelling is wrong of a named entity. Sentence tokenizer is required to provide context for spelling correction, so i am afraid I cannot do much at this point. I am occupied at present but once i get free I will surely have a look into [dacy](https://github.com/KennethEnevoldsen/DaCy) and ways I can modify contextualSpellCheck to make it more generalized.

**Comment by KennethEnevoldsen** [comment]
Sure thing, I naturally fully understand that you have other things. The reason I wanted to add a spelling correction module to the spacy pipeline to actually because relative modest spelling errors seem to influence the model performance notably. There is a more detailed explanation on this [here](https://centre-for-humanities-computing.github.io/DaCy/robustness.html).

**Comment by R1j1t** [comment]
I completely understand, will surely have try to contribute!!
