### ISSUE TITLE
Methodology for spell check

### ISSUE THREAD

**Issue by dsvrsec** [R1j1t/contextualSpellCheck#67]
Can you please mention the methodology followed in detection and correction of mispelled words,may be at higher level,if possible, thank you

**Comment by R1j1t** [comment]
Hey @dsvrsec, I have mentioned this in my comments here: https://github.com/R1j1t/contextualSpellCheck/issues/59#issuecomment-811322409
>The current logic for spelling correction is as follows:
> 
> 1. provide spacy model: This will break the sentence into tokens. Now as this model is trained on a particular language (tweet specific models are also there) it knows the nuances
> 
> 2. Check the token in the transformer model's vocab: If the token is not present consider it spelling error
> 
> 3. Mask the OOV word and use the transformers model to predict words to replace mask
> 
> 4. check the edit distance to see which is closest syntactically.
> 
> 
> The default model (bert-base-cased) 

Please let me know if you have any questions, also feel free to contribute!!

**Comment by Xiaoping777** [comment]
Hi here, actually I compared the output with pyspellchecker package, which is purely based on the edit distance, the results is almost same. Just wondering, if there are some grammar correct included is the bert model in use?
