### ISSUE TITLE
add proxy setting when initialize "contextual spellchecker"

### ISSUE THREAD

**Issue by Xiaoping777** [R1j1t/contextualSpellCheck#68]
**Is your feature request related to a problem? Please describe.**
our work is behind a firewall, need a proxy setting to fetch the transformer model "bert-base-cased", I tried to download via "AutoTokenizer.from_pretrained('bert-base-cased', proxies={'http':PROXY, 'https':PROXY})"; however, looks like it cannot find the path. so I have to change 107 line by adding the proxy:
self.BertTokenizer = AutoTokenizer.from_pretrained(self.model_name, proxies={'http':PROXY, 'https':PROXY})

**Describe the solution you'd like**
I want the package can accept the proxy setting when initialize the class

**Describe alternatives you've considered**
or I can download via transformer from_pretrained function, while "contextual spellchecker" can find it properly

**Additional context**

**Comment by R1j1t** [comment]
This I think is a good enhancement to have, I will have a look and try to commit the same. If you think, you can contribute please feel free to open a PR. I would be more than happy to merge!
