### ISSUE TITLE
Enable github sponsorship to speed work

### ISSUE THREAD

**Issue by Hendler** [R1j1t/contextualSpellCheck#69]
https://github.blog/2020-03-24-getting-started-with-github-sponsors/

**Comment by R1j1t** [comment]
Hey, @Hendler, thank you so much for the suggestion. I did think about it, but Github does not support the sponsor button for my country. I could use some 3rd party accounts but never tried that route. 

If there is anything specific you can see in the package, please feel free to create a PR. It will help other users as well! Or you can make an issue for the enhancement. I don't see myself contributing a lot of code to the package for the next couple of months, but maybe after that, I will start adding features and make it ready for a v1 release!

**Comment by Hendler** [comment]
Hello, thank you.

 Maybe Patreon has a solution?

**Comment by R1j1t** [comment]
I will try over weekend for Patreon, thanks!
