### ISSUE TITLE
Single multilingual model recommendation?

### ISSUE THREAD

**Issue by nickchomey** [R1j1t/contextualSpellCheck#84]
Is there a single model that you would recommend using to autocorrect misspellings across common languages? Thanks!

**Comment by R1j1t** [comment]
Hey @nickchomey, I apologize for the late reply. The default model (`bert-base-cased`) sounds like a good model, but I know it is predominantly trained on English text. .As, my work did not require multilingual sentences, so I have little experience.

 **If you have any suggestions, please let me know**
