### ISSUE TITLE
How to use it efficiently in the pipeline?

### ISSUE THREAD

**Issue by mark-fangzhou-xie** [R1j1t/contextualSpellCheck#9]
Hi! Thanks for this package. I am trying to use this one with `sentencizer` and `merge_entities` pipelines but I am not sure what is the best way to combine them. My objective is to:

1. parse a long text into sentences
2. fix possible typos in sentences
3. tokenize each sentence, find and merge entities within sentences

What is more, when I tried to load checker in pipeline, it sometimes will return errors or does not find typos at all.

Information on package version:

<details><summary>system and package info:</summary>
<p>

```python
>>> spacy.__version__
'2.2.3'
>>> sys.version
'3.7.6 | packaged by conda-forge | (default, Dec 27 2019, 00:09:34) \n[GCC 7.3.0]'
```

</p>
</details>

Example of not fixing typo:

<details><summary>CLICK ME</summary>
<p>

```python
>>> nlp = spacy.load('en_core_web_sm')#, disable=["tagger", "parser"])
>>> merge_ents = nlp.create_pipe("merge_entities")
>>> checker = ContextualSpellCheck()
>>> nlp.add_pipe(checker)
>>> nlp.add_pipe(merge_ents)
>>> doc = nlp('Income was $9.4 milion compared to the prior year of $2.7 milion.')
>>> doc._.outcome_spellCheck
'Income was $9.4 milion compared million the prior year of $2.7 milion.'
```

</p>
</details>

Example of error output:

<details><summary>CLICK ME</summary>
<p>

```python
>>> nlp = spacy.load('en_core_web_sm', disable=["parser"]) #"tagger", 
>>> merge_ents = nlp.create_pipe("merge_entities")
>>> checker = ContextualSpellCheck()
>>> nlp.add_pipe(checker)
>>> nlp.add_pipe(merge_ents)
>>> doc = nlp('Income was $9.4 milion compared to the prior year of $2.7 milion.')
-------------------------------------------------------------------------------------------------
<stdin> 1 <module>
language.py 435 __call__
doc = proc(doc, **component_cfg.get(name, {}))
contextualSpellCheck.py 74 __call__
candidate = self.candidateGenerator(doc, misspellTokens)
contextualSpellCheck.py 183 candidateGenerator
for i in token.sent:
TypeError:
'NoneType' object is not iterable
```

</p>
</details>

I believe the error has something to do with the default `tagger` pipe. But still, loading the `merge_entities` pipe will somehow broke spell checking?

**Comment by R1j1t** [comment]
Hi @mark-fangzhou-xie, thanks for pointing out this issue. There are 2 questions in there. Let me first solve the 2nd question.

`TypeError: 'NoneType' object is not iterable`. To improve the performance what I have done is I am using the sentence to provide context to the model when correcting any misspell and not multiple sentences. For that I am relying on `token.sent`, which in-turn has [dependency on parser](https://github.com/explosion/spaCy/blob/master/spacy/tokens/doc.pyx#L618) else it returns `None`. I think I'll fix this by raising an error with a helpful error message. 

Now coming to the 1st question, because you are using  `merge_entities` what is happening is, the tokens are getting updated. Which results in funny responses from the extensions. To explain the issue I updated some debug prints below:

```py
>>> nlp = spacy.load('en_core_web_sm')
>>> merge_ents = nlp.create_pipe("merge_entities")
>>> nlp.add_pipe(checker)
>>> nlp.add_pipe(merge_ents)
>>> doc = nlp('Income was $9.4 milion compared to the prior year of $2.7 milion.')
[milion, milion]
milion Income was $9.4 milion compared to the prior year of $2.7 milion.

For `milion` updated query is:
 Income was $9.4 [MASK] compared to the prior year of $2.7 milion.
token_score:  [0.5942245125770569, 0.2434934675693512, 0.08809225261211395, 0.018352238461375237, 0.008257790468633175, 0.006722627207636833, 0.00590920215472579, 0.0037973211146891117, 0.00204941863194108, 0.0011264876229688525]
response[`milion`]:  ['million', 'billion', ',', 'trillion', 'Million', '%', '##M', 'annually', '##B', 'USD'] score[`milion`]:  [('million', 0.59422), ('billion', 0.24349), (',', 0.08809), ('trillion', 0.01835), ('Million', 0.00826), ('%', 0.00672), ('##M', 0.00591), ('annually', 0.0038), ('##B', 0.00205), ('USD', 0.00113)]
milion Income was $9.4 milion compared to the prior year of $2.7 milion.

For `milion` updated query is:
 Income was $9.4 milion compared to the prior year of $2.7 [MASK].
token_score:  [0.6593362092971802, 0.26184770464897156, 0.05391395464539528, 0.005098216235637665, 0.004251918755471706, 0.00267925881780684, 0.0015258868224918842, 0.0007733289967291057, 0.0005944302538409829, 0.00041259179124608636]
response[`milion`]:  ['billion', 'million', 'trillion', '##M', 'Million', '##B', 'USD', '##b', 'millions', '%'] score[`milion`]:  [('billion', 0.65934), ('million', 0.26185), ('trillion', 0.05391), ('##M', 0.0051), ('Million', 0.00425), ('##B', 0.00268), ('USD', 0.00153), ('##b', 0.00077), ('millions', 0.00059), ('%', 0.00041)]
misspellingsDict[misspell] ['million', 'billion', ',', 'trillion', 'Million', '%', '##M', 'annually', '##B', 'USD']
response[`milion`] million
misspellingsDict[misspell] ['billion', 'million', 'trillion', '##M', 'Million', '##B', 'USD', '##b', 'millions', '%']
response[`milion`] million
Final suggestions {milion: 'million', milion: 'million'}
>>>
```

If you see the last line from the debug, final suggestions `{milion: 'million', milion: 'million'}` are what we would expect. 

```py
>>> doc._.outcome_spellCheck
suggestions in outcome extension {to: 'million', : 'million'}
Did you mean:  Income was $9.4 milion compared million the prior year of $2.7 milion.
'Income was $9.4 milion compared million the prior year of $2.7 milion.'
>>> 
>>> for i in doc:
...     print("index: ",i.i,"text: ",i.text)
... 
index:  0 text:  Income
index:  1 text:  was
index:  2 text:  $9.4 milion
index:  3 text:  compared
index:  4 text:  to
index:  5 text:  the prior year
index:  6 text:  of
index:  7 text:  $2.7 milion
index:  8 text:  .
```
But when we call the `outcome_spellCheck` extension, the token has been updated and the earlier milion (index 4) is replaced by new index 4 (to) and so on. I think it will take some time, but i will fix it. If you think, you have an approach which will work please do create a PR.

**Comment by R1j1t** [comment]
I have completed the change. This is will set the corrected sentence at the time this package is executed in the pipeline. Also, if any other package modifies the position or text of misspell token, it will raise a warning.
