### ISSUE TITLE
Query - train/fine tune underlying model on own data

### ISSUE THREAD

**Issue by azzamnaeem** [R1j1t/contextualSpellCheck#90]
Hello,

Is it possible to fine tune the underlying BERT model on our own data before applying the contextual spell check with this package?

Thanks!

**Comment by R1j1t** [comment]
Could you refer to this discussion https://github.com/R1j1t/contextualSpellCheck/discussions/24? Hopefully it will answer your question, if not then please add more details and I can try to address them.

**Comment by azzamnaeem** [comment]
thank you!
